export const commonInterceptorConstants = {
    AUTH_HEADER: 'AUTH_HEADERS',
    LANGUAGE_PARAM: 'LANGUAGE_PARAM',
    REFERRAL_HEADERS: 'REFERRAL_HEADERS',
    NEXT_CACHE: 'NEXT_CACHE',
    USER_AUTH_HEADER: 'USER_AUTH_HEADERS'
};
